### ISSUE TITLE
Option for Swift Playgrounds?

### ISSUE THREAD

**Issue by briancpark** [SwiftProcessing/SwiftProcessing#37]
As I'm studying more Swift development, I noticed Swift Playgrounds could be a more lightweight version to run than running sketches on an iOS device or simulator. Also has the advantage to code, compile, and run on iPad version of the Playgrounds app. 

Is there a way to port the API to the Playgrounds app?

**Comment by jjkaufman** [comment]
Swift Playgrounds are very cool! I was very excited when I saw them come out on MacOS. 

It should be possible. There may be a few technical considerations getting it to run in Swift Playgrounds, but I think the real effort would be to create a compelling playground. It would almost be like writing a book / documentation

**Comment by briancpark** [comment]
Thank you for the feedback. Do you know exactly how I can import it? I cannot add a package dependency under File->Swift Packages. The option is grayed out in Playgrounds, so I am wondering if you've had success? If not, a [StackOverflow post](https://stackoverflow.com/questions/60352804/how-to-import-swift-package-in-playground) explains some third party ways to install a package that I'll try later.

The reason why I'm asking is because I am interested in using this open source library for the [Swift Student Challenge](https://developer.apple.com/wwdc20/swift-student-challenge/) for WWDC 2020.

**Comment by unoctanium** [comment]
Here is how I made it work in Swift Playgrounds on my iPad:

1. Open Playgrounds on the iPad and create a new app
2. In github, copy the link to the github repo of SwiftPlaygrounds (https://github.com/SwiftProcessing/SwiftProcessing.git) and paste it into Swift playgrounds Add package window (Add button right side of sidebar / Swift package / package URL / Add to project)
3. Add a new Swift file: ProcessingView with following content

```
import SwiftUI

struct ProcessingView: UIViewRepresentable {
    
    func makeUIView(context: Context) -> UIView {
        return MySketch()
    }
    
    func updateUIView(_ uiView: UIView, context: Context) {}
}

```

4. Add a new file MySketch with the following content:

```
import SwiftProcessing
import UIKit

class MySketch: Sketch, SketchDelegate {
    
    func setup() {
        
    }
    
    func draw() {
        fill(255, 0, 0)
        circle(125, 125, 50)
    }
}

```

5. Change content of file MyApp to:

```
import SwiftUI

@main
struct MyApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

6. Run and be happy
